math:
  katex:
    enable: true
search:
  path: search.xml
  field: post
  content: true
  format: html
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false
avatar: 
  url: /images/ggg.jpg